"""empty message

Revision ID: 004934dbf394
Revises: 19501d9c3874
Create Date: 2022-04-10 19:56:35.818265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004934dbf394'
down_revision = '19501d9c3874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
