"""empty message

Revision ID: 19501d9c3874
Revises: dc28dc92df12
Create Date: 2022-04-10 19:55:20.807584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19501d9c3874'
down_revision = 'dc28dc92df12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
