"""migrate db model to the database

Revision ID: 94045c36d0ee
Revises: 155cdeef4cbe
Create Date: 2022-03-10 14:43:03.148233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94045c36d0ee'
down_revision = '155cdeef4cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
